services:
  backend:
    build:
      target: dev
    command: npm run dev
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

  auth:
    build:
      target: dev
    command: npm run devAuth
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

  frontend:
    build:
      target: dev
    command: npm run dev -- --host 0.0.0.0 --port 5173
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: ${VITE_API_URL}
      VITE_AUTH_URL: ${VITE_AUTH_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
